# Generated by Django 3.0 on 2019-12-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Fundamental'), (2, 'Médio'), (3, 'Superior'), (4, 'Técnico'), (5, 'Profissional')])),
                ('turno', models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Notruno'), (4, 'Integral')])),
            ],
        ),
    ]
