# Generated by Django 3.0 on 2019-12-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoEnsino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.IntegerField(choices=[(1, 'Matutino'), (2, 'Vespertino'), (3, 'Noturno'), (4, 'Integral')]),
        ),
    ]
