# Generated by Django 3.0 on 2019-12-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aluno_telefonealuno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(default='av', max_length=100),
        ),
    ]
